export const config = {
  REACT_APP_URL: process.env.REACT_APP_URL,
  REACT_APP_PORTALS_URL: process.env.REACT_APP_PORTALS_URL,
  REACT_APP_PORTALS_REMOTE: process.env.REACT_APP_PORTALS_REMOTE,
  REACT_APP_NODE_ENV: process.env.REACT_APP_NODE_ENV,
  REACT_APP_LANG_STORAGE: process.env.REACT_APP_LANG_STORAGE,
};
